version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: task_manager_backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    ports:
      - "4000:4000"
    depends_on:
      - mongo

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task_manager_frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend

  mongo:
    image: mongo:6.0
    container_name: task_manager_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
